var annotated_dup =
[
    [ "LIVINGHOUSE", "namespace_l_i_v_i_n_g_h_o_u_s_e.html", [
      [ "App", "namespace_l_i_v_i_n_g_h_o_u_s_e_1_1_app.html", [
        [ "AudioController", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_audio_controller.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_audio_controller" ],
        [ "BlueEyeState", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_blue_eye_state.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_blue_eye_state" ],
        [ "BuffCantMove", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_cant_move.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_cant_move" ],
        [ "BuffDamage", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_damage.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_damage" ],
        [ "BuffHeal", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_heal.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_heal" ],
        [ "BuffMoveSpeedDown", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_move_speed_down.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_move_speed_down" ],
        [ "BuffMoveSpeedUp", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_move_speed_up.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_move_speed_up" ],
        [ "BuffStaminaDown", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_down.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_down" ],
        [ "BuffStaminaDurationDown", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_duration_down.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_duration_down" ],
        [ "BuffStaminaDurationUp", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_duration_up.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_duration_up" ],
        [ "BuffStaminaSpeedDown", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_speed_down.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_speed_down" ],
        [ "BuffStaminaSpeedUp", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_speed_up.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_speed_up" ],
        [ "BuffStaminaUp", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_up.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_buff_stamina_up" ],
        [ "Character", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_character.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_character" ],
        [ "CheckKeyEvent", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_check_key_event.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_check_key_event" ],
        [ "DemoCameraController", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_demo_camera_controller.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_demo_camera_controller" ],
        [ "DoorInteractEvent", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_door_interact_event.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_door_interact_event" ],
        [ "DoorState", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_door_state.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_door_state" ],
        [ "EMFMeterState", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_e_m_f_meter_state.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_e_m_f_meter_state" ],
        [ "Enemy01", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_enemy01.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_enemy01" ],
        [ "Enemy02", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_enemy02.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_enemy02" ],
        [ "EnemyController", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_enemy_controller.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_enemy_controller" ],
        [ "EventRunner", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_event_runner.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_event_runner" ],
        [ "FollowCamera", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_follow_camera.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_follow_camera" ],
        [ "GimmickRayHitEvent", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_gimmick_ray_hit_event.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_gimmick_ray_hit_event" ],
        [ "HitObject_WaterGun", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_hit_object___water_gun.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_hit_object___water_gun" ],
        [ "HitObjectData", "struct_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_hit_object_data.html", "struct_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_hit_object_data" ],
        [ "HitObjectEmitter", "struct_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_hit_object_emitter.html", "struct_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_hit_object_emitter" ],
        [ "IBuff", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_buff.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_buff" ],
        [ "ICanMoveObject", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_can_move_object.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_can_move_object" ],
        [ "ICharacterController", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_character_controller.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_character_controller" ],
        [ "ICharacterState", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_character_state.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_character_state" ],
        [ "IEnemy", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_enemy.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_enemy" ],
        [ "IEvent", "interface_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_event.html", "interface_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_event" ],
        [ "IHitObject", "interface_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_hit_object.html", "interface_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_hit_object" ],
        [ "IItem", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_item.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_item" ],
        [ "IPoint", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_point.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_point" ],
        [ "IScouter", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_scouter.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_i_scouter" ],
        [ "ItemInteractEvent", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_interact_event.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_interact_event" ],
        [ "ItemRayHitEvent", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_ray_hit_event.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_ray_hit_event" ],
        [ "ItemSelectorSlot", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_selector_slot.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_selector_slot" ],
        [ "ItemSlot", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_slot.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_item_slot" ],
        [ "KeyOminouse", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_key_ominouse.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_key_ominouse" ],
        [ "KeyStandard", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_key_standard.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_key_standard" ],
        [ "Player", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_player.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_player" ],
        [ "PlayerController", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_player_controller.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_player_controller" ],
        [ "PointEnemySpawner", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_point_enemy_spawner.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_point_enemy_spawner" ],
        [ "PointItemSpawner", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_point_item_spawner.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_point_item_spawner" ],
        [ "PointPatroll", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_point_patroll.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_point_patroll" ],
        [ "RainCoat", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_rain_coat.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_rain_coat" ],
        [ "RedEye", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_red_eye.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_red_eye" ],
        [ "ScouterEnemy01", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_scouter_enemy01.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_scouter_enemy01" ],
        [ "ScouterEnemy02", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_scouter_enemy02.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_scouter_enemy02" ],
        [ "Strawdowll", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_strawdowll.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_strawdowll" ],
        [ "Umbrella", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_umbrella.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_umbrella" ],
        [ "WarterGun", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_warter_gun.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_app_1_1_warter_gun" ]
      ] ],
      [ "Attribute", "namespace_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute.html", [
        [ "LabelAttribute", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_label_attribute.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_label_attribute" ],
        [ "NameAttribute", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_name_attribute.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_name_attribute" ],
        [ "ReadOnlyAttribute", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_read_only_attribute.html", null ],
        [ "ReadOnlyDrawer", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_read_only_drawer.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_read_only_drawer" ],
        [ "SubclassSelectorAttribute", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_subclass_selector_attribute.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_attribute_1_1_subclass_selector_attribute" ]
      ] ],
      [ "Manager", "namespace_l_i_v_i_n_g_h_o_u_s_e_1_1_manager.html", [
        [ "ApplicationManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_application_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_application_manager" ],
        [ "BuffManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_buff_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_buff_manager" ],
        [ "CameraManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_camera_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_camera_manager" ],
        [ "CharacterManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_character_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_character_manager" ],
        [ "CommonManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_common_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_common_manager" ],
        [ "FrameManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_frame_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_frame_manager" ],
        [ "HitObjectManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_hit_object_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_hit_object_manager" ],
        [ "InputManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_input_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_input_manager" ],
        [ "ItemManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_item_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_item_manager" ],
        [ "ItemSlotManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_item_slot_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_item_slot_manager" ],
        [ "LayerManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_layer_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_layer_manager" ],
        [ "ResourceManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_resource_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_resource_manager" ],
        [ "SceneManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_scene_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_scene_manager" ],
        [ "WipeManager", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_wipe_manager.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_manager_1_1_wipe_manager" ]
      ] ],
      [ "Scene", "namespace_l_i_v_i_n_g_h_o_u_s_e_1_1_scene.html", [
        [ "Game", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_scene_1_1_game.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_scene_1_1_game" ],
        [ "IScene", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_scene_1_1_i_scene.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_scene_1_1_i_scene" ],
        [ "Title", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_scene_1_1_title.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_scene_1_1_title" ]
      ] ],
      [ "SO", "namespace_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o.html", [
        [ "BuffScriptableObject", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_buff_scriptable_object.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_buff_scriptable_object" ],
        [ "CacheEventSO", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_cache_event_s_o.html", null ],
        [ "CharacterScriptableObject", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_character_scriptable_object.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_character_scriptable_object" ],
        [ "EventScriptableObject", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_event_scriptable_object.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_event_scriptable_object" ],
        [ "ItemScriptableObject", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_item_scriptable_object.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_item_scriptable_object" ],
        [ "ItemSlotScriptableObject", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_item_slot_scriptable_object.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_item_slot_scriptable_object" ],
        [ "ItemSpawnScriptableObject", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_item_spawn_scriptable_object.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_s_o_1_1_item_spawn_scriptable_object" ]
      ] ],
      [ "Utility", "namespace_l_i_v_i_n_g_h_o_u_s_e_1_1_utility.html", [
        [ "CustomMonoBehaviour", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_custom_mono_behaviour.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_custom_mono_behaviour" ],
        [ "DisableNotifyMonoBehaviour", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_disable_notify_mono_behaviour.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_disable_notify_mono_behaviour" ],
        [ "KeyAndValue", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_key_and_value.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_key_and_value" ],
        [ "SerializeInterface", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_serialize_interface.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_serialize_interface" ],
        [ "Singleton", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_singleton.html", null ],
        [ "SingletonMonoBehaviour", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_singleton_mono_behaviour.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_singleton_mono_behaviour" ],
        [ "TableBase", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_table_base.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_table_base" ],
        [ "UnsafeList", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_unsafe_list.html", "class_l_i_v_i_n_g_h_o_u_s_e_1_1_utility_1_1_unsafe_list" ]
      ] ]
    ] ]
];